/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import java.util.Random;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.util.regex.*;
import javax.swing.JOptionPane;

/**
 *
 * @author James
 */
public class LoanBank extends javax.swing.JFrame {

    public MainFrame mf;
    double totalMoney;
    public double UpdateBalance;
    double ValueToAll;
    double AmountToPay;
    
     public Random AccNo1 = new Random();
     public Random AccNo2 = new Random();
     public Random AccNo3 = new Random();
     
     public Pattern NumberException;
     
     public Matcher FindNumberException;
     
    public int AccountJohn = 111111111;
    public int AccountJack = 222222222;
    public int AccountJhun = 333333333;
    
//    public int AccountJohn = AccNo1.nextInt(10000000);
//    public int AccountJack = AccNo2.nextInt(10000000);
//    public int AccountJhun = AccNo3.nextInt(10000000);
     
     MenuBank mb;
        
    /**
     * Creates new form LoanBank
     */
    public LoanBank(MenuBank menuBanking) {
        initComponents();
        this.mb = menuBanking;
        
        AccNoJohn.setText("" + Integer.toString(AccountJohn));
        AccNoJack.setText("" + Integer.toString(AccountJack));
        AccNoJhun.setText("" + Integer.toString(AccountJhun));
        setTitle("Im gonna Loan");
        BackToMenuBTN.setVisible(false);
        mb.addMoney = AmountToPay;
        
        
    }
    public void addTable(String name, int ACC_NO, double RemainingBal, double Loaned) {
    DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();


    Vector<Object> v = new Vector<>();
        v.add(name);
        v.add(ACC_NO);
        v.add(RemainingBal);
        v.add(Loaned);
        dt.addRow(v);

    // Calculate loan after updating/adding the row
    toCalculateLoan();
   }
    
    public void toCalculateLoan(){
       double numberOfRows = jTable1.getRowCount();
       totalMoney = 0.00;
       
       for(int i = 0; i < numberOfRows; i++){
           double value = Double.valueOf(jTable1.getValueAt(i,3).toString());
           totalMoney += value;
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        EnterName = new javax.swing.JLabel();
        TF_EnterName = new javax.swing.JTextField();
        EnterName1 = new javax.swing.JLabel();
        TF_AccountNumber = new javax.swing.JTextField();
        LoanButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TF_Balance = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        PanelForJohn = new javax.swing.JPanel();
        Name1 = new javax.swing.JLabel();
        AccountNumberForJohn = new javax.swing.JLabel();
        LabelName1 = new javax.swing.JLabel();
        AccNoJohn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NameJohn = new javax.swing.JLabel();
        BalForJohn = new javax.swing.JLabel();
        BalJohn = new javax.swing.JLabel();
        PanelForJhun = new javax.swing.JPanel();
        Name3 = new javax.swing.JLabel();
        AccountNumberForJack1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AccNoJhun = new javax.swing.JLabel();
        NameJhun = new javax.swing.JLabel();
        BalForJhun = new javax.swing.JLabel();
        BalJhun = new javax.swing.JLabel();
        BackToMenuBTN = new javax.swing.JButton();
        PayLoans = new javax.swing.JButton();
        PanelForJack = new javax.swing.JPanel();
        Name2 = new javax.swing.JLabel();
        AccountNumberForJack = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NameJack = new javax.swing.JLabel();
        AccNoJack = new javax.swing.JLabel();
        BalForJack = new javax.swing.JLabel();
        BalJack = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        RemoveBTN = new javax.swing.JButton();
        DPTS_Money = new javax.swing.JButton();
        SavingsAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EnterName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EnterName.setText("Enter the name:");

        TF_EnterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_EnterNameActionPerformed(evt);
            }
        });

        EnterName1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EnterName1.setText("Enter the Account No.:");

        TF_AccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_AccountNumberActionPerformed(evt);
            }
        });

        LoanButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LoanButton.setText("LOAN");
        LoanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Enter Balance:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(EnterName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                        .addComponent(EnterName1)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_EnterName, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LoanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TF_AccountNumber))
                        .addGap(18, 18, 18))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterName)
                    .addComponent(EnterName1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_EnterName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_AccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Name1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Name1.setText("Name:");

        AccountNumberForJohn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccountNumberForJohn.setText("Account No.:");

        LabelName1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        AccNoJohn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel1.setText("----------------------------------------------------------------------------------");

        jLabel3.setText("----------------------------------------------------------------------------------");

        NameJohn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NameJohn.setText("John");

        BalForJohn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BalForJohn.setText("Balance:");

        BalJohn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BalJohn.setText("500000");

        javax.swing.GroupLayout PanelForJohnLayout = new javax.swing.GroupLayout(PanelForJohn);
        PanelForJohn.setLayout(PanelForJohnLayout);
        PanelForJohnLayout.setHorizontalGroup(
            PanelForJohnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelForJohnLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PanelForJohnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelForJohnLayout.createSequentialGroup()
                        .addComponent(Name1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NameJohn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(LabelName1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelForJohnLayout.createSequentialGroup()
                        .addComponent(AccountNumberForJohn)
                        .addGap(18, 18, 18)
                        .addComponent(AccNoJohn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelForJohnLayout.createSequentialGroup()
                        .addComponent(BalForJohn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BalJohn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelForJohnLayout.setVerticalGroup(
            PanelForJohnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelForJohnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelForJohnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelForJohnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Name1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addComponent(NameJohn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LabelName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelForJohnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AccountNumberForJohn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(AccNoJohn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelForJohnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BalForJohn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalJohn, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        Name3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Name3.setText("Name:");

        AccountNumberForJack1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccountNumberForJack1.setText("Account No.:");

        jLabel5.setText("----------------------------------------------------------------------------------");

        jLabel6.setText("----------------------------------------------------------------------------------");

        AccNoJhun.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        NameJhun.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NameJhun.setText("Jhun");

        BalForJhun.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BalForJhun.setText("Balance:");

        BalJhun.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BalJhun.setText("500000");

        javax.swing.GroupLayout PanelForJhunLayout = new javax.swing.GroupLayout(PanelForJhun);
        PanelForJhun.setLayout(PanelForJhunLayout);
        PanelForJhunLayout.setHorizontalGroup(
            PanelForJhunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelForJhunLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(PanelForJhunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelForJhunLayout.createSequentialGroup()
                        .addComponent(BalForJhun)
                        .addGap(18, 18, 18)
                        .addComponent(BalJhun, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelForJhunLayout.createSequentialGroup()
                        .addComponent(AccountNumberForJack1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccNoJhun, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelForJhunLayout.createSequentialGroup()
                        .addComponent(Name3)
                        .addGap(18, 18, 18)
                        .addComponent(NameJhun, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelForJhunLayout.setVerticalGroup(
            PanelForJhunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelForJhunLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addGroup(PanelForJhunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Name3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameJhun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(PanelForJhunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountNumberForJack1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccNoJhun, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelForJhunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BalForJhun)
                    .addComponent(BalJhun, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(9, 9, 9))
        );

        BackToMenuBTN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackToMenuBTN.setText("Back to Menu");
        BackToMenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuBTNActionPerformed(evt);
            }
        });

        PayLoans.setBackground(new java.awt.Color(204, 255, 204));
        PayLoans.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PayLoans.setText("Pay Loans");
        PayLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayLoansActionPerformed(evt);
            }
        });

        Name2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Name2.setText("Name:");

        AccountNumberForJack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccountNumberForJack.setText("Account No.:");

        jLabel2.setText("----------------------------------------------------------------------------------");

        jLabel4.setText("----------------------------------------------------------------------------------");

        NameJack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NameJack.setText("Jack");

        AccNoJack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        BalForJack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BalForJack.setText("Balance:");

        BalJack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BalJack.setText("500000");

        javax.swing.GroupLayout PanelForJackLayout = new javax.swing.GroupLayout(PanelForJack);
        PanelForJack.setLayout(PanelForJackLayout);
        PanelForJackLayout.setHorizontalGroup(
            PanelForJackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelForJackLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PanelForJackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelForJackLayout.createSequentialGroup()
                        .addGroup(PanelForJackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelForJackLayout.createSequentialGroup()
                                .addComponent(BalForJack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BalJack, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelForJackLayout.createSequentialGroup()
                                .addComponent(AccountNumberForJack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AccNoJack, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelForJackLayout.createSequentialGroup()
                                .addComponent(Name2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NameJack, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelForJackLayout.setVerticalGroup(
            PanelForJackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelForJackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelForJackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameJack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelForJackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelForJackLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AccountNumberForJack, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AccNoJack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelForJackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BalForJack)
                    .addComponent(BalJack, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(BackToMenuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PayLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelForJack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelForJohn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PanelForJhun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelForJohn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelForJack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelForJhun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackToMenuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PayLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Account No.", "Remaining Bal.", "Loaned"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        RemoveBTN.setBackground(new java.awt.Color(255, 204, 204));
        RemoveBTN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RemoveBTN.setText("Remove");
        RemoveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBTNActionPerformed(evt);
            }
        });

        DPTS_Money.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DPTS_Money.setText("Deposit Money");
        DPTS_Money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DPTS_MoneyActionPerformed(evt);
            }
        });

        SavingsAccount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SavingsAccount.setText("See Savings Account");
        SavingsAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingsAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RemoveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DPTS_Money, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SavingsAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addGap(69, 69, 69))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RemoveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(DPTS_Money, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(SavingsAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToMenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuBTNActionPerformed
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                mb.setVisible(true);
            }
        });
    }//GEN-LAST:event_BackToMenuBTNActionPerformed

    private void LoanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanButtonActionPerformed
    
        
        NumberException = Pattern.compile("[0-9]+");
        
        
        String GrabName = TF_EnterName.getText();
        String GrabAccNo = TF_AccountNumber.getText();
        String GrabBalance = TF_Balance.getText();
        
        FindNumberException = NumberException.matcher(GrabName);

        
        if(FindNumberException.find()){
            JOptionPane.showMessageDialog(null,"Invalid! name cannot have any number.","Invalid",JOptionPane.ERROR_MESSAGE);
        } else {
         try {
             if(GrabAccNo.isEmpty() || GrabBalance.isEmpty()){
                JOptionPane.showMessageDialog(null,"Invalid! Fill up the Spaces .","Invalid",JOptionPane.ERROR_MESSAGE);
            } else {
            int AccountNumber = Integer.parseInt(GrabAccNo);
            double Balance = Double.parseDouble(GrabBalance);
            
            double GrabBalanceForJohn = Double.parseDouble(BalJohn.getText());
            double GrabBalanceForJack = Double.parseDouble(BalJack.getText());
            double GrabBalanceForJhun = Double.parseDouble(BalJhun.getText());
            if(GrabName.equals("John")){
                if(AccountNumber == AccountJohn){
                    if(Balance <= 0){
                        JOptionPane.showMessageDialog(null,"Invalid! Balance must be an Integer .","Invalid",JOptionPane.ERROR_MESSAGE);
                    } else if(Balance > GrabBalanceForJohn){
                        JOptionPane.showMessageDialog(null,"Invalid! Balance Exceeding the user balanced. .","Invalid",JOptionPane.ERROR_MESSAGE);
                    } else {
                        double UpdateBalanceJohn = GrabBalanceForJohn - Balance;
                        BalJohn.setText("" +  UpdateBalanceJohn);
                        mb.addMoney = mb.addMoney + Balance;
                        addTable(GrabName,AccountJohn,UpdateBalanceJohn,Balance);
                    }
                }
                else {
                   JOptionPane.showMessageDialog(null,"Invalid! Account number for " + GrabName + " is not the same.","Invalid",JOptionPane.ERROR_MESSAGE);
                }
            } else if(GrabName.equals("Jack")){
                if(AccountNumber == AccountJack){
                    if(Balance <= 0){
                        JOptionPane.showMessageDialog(null,"Invalid! Balance must be an Integer .","Invalid",JOptionPane.ERROR_MESSAGE);
                    } else if(Balance > GrabBalanceForJack){
                        JOptionPane.showMessageDialog(null,"Invalid! Balance Exceeding the user balanced. .","Invalid",JOptionPane.ERROR_MESSAGE);
                    } else {
                        double UpdateBalanceJack = GrabBalanceForJack - Balance;
                        BalJack.setText("" +  UpdateBalanceJack);
                        mb.addMoney = mb.addMoney + Balance;
                        addTable(GrabName,AccountJohn,UpdateBalanceJack,Balance);
                    }
                }
                else {
                   JOptionPane.showMessageDialog(null,"Invalid! Account number for " + GrabName + " is not the same.","Invalid",JOptionPane.ERROR_MESSAGE);
                }
            }
            else if(GrabName.equals("Jhun")){
                if(AccountNumber == AccountJhun){
                    if(Balance <= 0){
                        JOptionPane.showMessageDialog(null,"Invalid! Balance must be an Integer .","Invalid",JOptionPane.ERROR_MESSAGE);
                    } else if(Balance > GrabBalanceForJack){
                        JOptionPane.showMessageDialog(null,"Invalid! Balance Exceeding the user balanced. .","Invalid",JOptionPane.ERROR_MESSAGE);
                    } else {
                        double UpdateBalanceJhun = GrabBalanceForJhun - Balance;
                        BalJack.setText("" +  UpdateBalanceJhun);
                        mb.addMoney = mb.addMoney + Balance;
                        addTable(GrabName,AccountJohn,UpdateBalanceJhun,Balance);
                    }
                }
                else {
                   JOptionPane.showMessageDialog(null,"Invalid! Account number for " + GrabName + " is not the same.","Invalid",JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null,"It seems that i can't find you were looking for.","Cannot Find",JOptionPane.PLAIN_MESSAGE);
            }
             }
         } catch(NumberFormatException e){
             JOptionPane.showMessageDialog(null,"Invalid! Account/Balance must be a number and double.","Invalid",JOptionPane.ERROR_MESSAGE);
         }
        }
    
        
    }//GEN-LAST:event_LoanButtonActionPerformed

    private void TF_EnterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_EnterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_EnterNameActionPerformed

    private void TF_AccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_AccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_AccountNumberActionPerformed

    private void DPTS_MoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DPTS_MoneyActionPerformed
        try {
        String inputMoney = JOptionPane.showInputDialog(null,"Please Enter an Amount: ","Depositing Money",JOptionPane.PLAIN_MESSAGE);
        if(inputMoney.isEmpty()){
            JOptionPane.showMessageDialog(null,"What?????","Error",JOptionPane.ERROR_MESSAGE);
        }
      mb.Money = Double.parseDouble(inputMoney);
      
      
      
      if(mb.Money < 0){
          JOptionPane.showMessageDialog(null, "Money Cannot be negative!","Invalid",JOptionPane.ERROR_MESSAGE);
      } else {
      mb.addMoney += mb.Money;
      
      mb.SavingsAccount.append("\t          You Deposited: " + String.format("%.2f", mb.Money) + "$");
      mb.SavingsAccount.append("\n");
      }
      } catch(NumberFormatException e){
          JOptionPane.showMessageDialog(null, "Invalid Inputation!","Invalid",JOptionPane.ERROR_MESSAGE);
      } 
     
    }//GEN-LAST:event_DPTS_MoneyActionPerformed

    private void SavingsAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingsAccountActionPerformed
      JOptionPane.showMessageDialog(null,"Total Balance: "+String.format("%.2f", mb.addMoney)+"$","Savings Account",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_SavingsAccountActionPerformed

    private void PayLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayLoansActionPerformed
        ValueToAll = 0;
        AmountToPay = 0;
        int NumberOfRows = jTable1.getRowCount();
        for(int i = 0; i < NumberOfRows; i++){
           ValueToAll = Double.parseDouble(jTable1.getValueAt(i,3).toString());
           AmountToPay += ValueToAll;
        }
        
        double VAT = 0.12;
        double TotalLoanVAT = AmountToPay * VAT;
        double TotalPay = AmountToPay + TotalLoanVAT;
        
        int YESNO = JOptionPane.showConfirmDialog(null,"Total: " + AmountToPay + "\n Total with 12% Tax: " +String.format("%.2f", AmountToPay) +"Would you like to Pay?", "PayLoan?", JOptionPane.YES_NO_OPTION);
        
        if(YESNO == JOptionPane.YES_OPTION){
            if(mb.addMoney < AmountToPay){
                JOptionPane.showMessageDialog(null,"Insufficient Balance","ERROR",JOptionPane.ERROR_MESSAGE);
            } else {
                mb.addMoney -= AmountToPay;
                JOptionPane.showMessageDialog(null,"Successfull paying","SUCCESS!",JOptionPane.INFORMATION_MESSAGE);
                BackToMenuBTN.setVisible(true);
            }
        } else {
            // Nothing to do here.
        }
//        int NumberOfRows = jTable1.getRowCount();
        
//        mb.LoaningAccount.setLength(0);
        
        for(int i = 0; i < NumberOfRows; i++){
           mb.LoaningAccount.append("\nName: " + String.valueOf(jTable1.getValueAt(i,0).toString() + "You Loaned: " + String.valueOf(jTable1.getValueAt(i,3).toString())));
           mb.LoaningAccount.append("\n");
        }
        
    }//GEN-LAST:event_PayLoansActionPerformed

    private void RemoveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBTNActionPerformed
        
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();;
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Please Select first after you click the remove button..","Error", JOptionPane.ERROR_MESSAGE);
        } else {
        // Get the remaining balance from the selected row
        double remainingBalance = (double) jTable1.getValueAt(selectedRow, 2);

        // Get the loaned amount from the selected row
        double loanedAmount = (double) jTable1.getValueAt(selectedRow, 3);

        // Update the remaining balance (subtract the loaned amount)
        UpdateBalance = remainingBalance - loanedAmount;

        // Remove the row from the table
        dt.removeRow(selectedRow);

    }
        
    }//GEN-LAST:event_RemoveBTNActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccNoJack;
    private javax.swing.JLabel AccNoJhun;
    private javax.swing.JLabel AccNoJohn;
    private javax.swing.JLabel AccountNumberForJack;
    private javax.swing.JLabel AccountNumberForJack1;
    private javax.swing.JLabel AccountNumberForJohn;
    private javax.swing.JButton BackToMenuBTN;
    private javax.swing.JLabel BalForJack;
    private javax.swing.JLabel BalForJhun;
    private javax.swing.JLabel BalForJohn;
    private javax.swing.JLabel BalJack;
    private javax.swing.JLabel BalJhun;
    private javax.swing.JLabel BalJohn;
    private javax.swing.JButton DPTS_Money;
    private javax.swing.JLabel EnterName;
    private javax.swing.JLabel EnterName1;
    private javax.swing.JLabel LabelName1;
    private javax.swing.JButton LoanButton;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel NameJack;
    private javax.swing.JLabel NameJhun;
    private javax.swing.JLabel NameJohn;
    private javax.swing.JPanel PanelForJack;
    private javax.swing.JPanel PanelForJhun;
    private javax.swing.JPanel PanelForJohn;
    private javax.swing.JButton PayLoans;
    private javax.swing.JButton RemoveBTN;
    private javax.swing.JButton SavingsAccount;
    private javax.swing.JTextField TF_AccountNumber;
    private javax.swing.JTextField TF_Balance;
    private javax.swing.JTextField TF_EnterName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
