/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;

/**
 *
 * @author James
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    public Pattern NumberException;
    public Pattern LetterException;
    public Pattern SpecialCharacterException;
    public Pattern WhiteSpaceTrace;
    
    public Matcher MatchPNumber;
    public Matcher MatchPLetter;
    public Matcher MatchSCharacter;
    public Matcher MatchSAccountNo;
    public Matcher MatchWhiteSpace;
    
    
    public MainFrame() {
        initComponents();
        setTitle("Grand Summit Bank System");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BankLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        UserName = new javax.swing.JTextField();
        ACCOUNT_NO = new javax.swing.JTextField();
        LB_NAME = new javax.swing.JLabel();
        LB_ACCNO = new javax.swing.JLabel();
        BTN_EXIT = new javax.swing.JButton();
        TO_PROCEED = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BankLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BankLabel.setText("Grand Summit Bank System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(BankLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BankLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });

        LB_NAME.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LB_NAME.setText("NAME:");

        LB_ACCNO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LB_ACCNO.setText("ACCOUNT NO :");

        BTN_EXIT.setBackground(new java.awt.Color(255, 127, 127));
        BTN_EXIT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BTN_EXIT.setForeground(new java.awt.Color(255, 255, 255));
        BTN_EXIT.setText("EXIT");
        BTN_EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EXITActionPerformed(evt);
            }
        });

        TO_PROCEED.setBackground(new java.awt.Color(144, 238, 144));
        TO_PROCEED.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TO_PROCEED.setForeground(new java.awt.Color(255, 255, 255));
        TO_PROCEED.setText("PROCEED");
        TO_PROCEED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TO_PROCEEDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(LB_ACCNO))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LB_NAME)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ACCOUNT_NO, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(BTN_EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TO_PROCEED)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_NAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACCOUNT_NO, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_ACCNO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTN_EXIT, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(TO_PROCEED, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        //
    }//GEN-LAST:event_UserNameActionPerformed

    private void BTN_EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EXITActionPerformed
             setVisible(false);
             
    }//GEN-LAST:event_BTN_EXITActionPerformed

    private void TO_PROCEEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TO_PROCEEDActionPerformed
       
        NumberException = Pattern.compile("[0-9]");
        LetterException = Pattern.compile("[a-zA-Z]");
        SpecialCharacterException = Pattern.compile("[$&+,:;=?@#|'<>.-^*()%!]");
        WhiteSpaceTrace = Pattern.compile("\\s+");
        
        String getUserName = UserName.getText();
        String getAccNumber = ACCOUNT_NO.getText();
        
        MatchPNumber = NumberException.matcher(getUserName);
        MatchPLetter = LetterException.matcher((getAccNumber));
//       MatchSCharacter = SpecialCharacterException.matcher(getUserName);
        MatchSAccountNo = SpecialCharacterException.matcher(getAccNumber);
        MatchWhiteSpace = WhiteSpaceTrace.matcher(getUserName);
        
        
        if(getUserName.isEmpty() && getAccNumber.isEmpty()){
            JOptionPane.showMessageDialog(null,"Fill up the spaces.","Invalid.",JOptionPane.ERROR_MESSAGE);
        } else if (getUserName.isEmpty()){
            JOptionPane.showMessageDialog(null,"Fill up the name please.","Invalid.",JOptionPane.ERROR_MESSAGE);
        } else if (getAccNumber.isEmpty()){
            JOptionPane.showMessageDialog(null,"Fill up the Account number please.","Invalid",JOptionPane.ERROR_MESSAGE);
        }
        else if(MatchPNumber.find()){
            JOptionPane.showMessageDialog(null,"Names Cannot contains any number.","Invalid",JOptionPane.ERROR_MESSAGE);
        } else if(MatchPLetter.find()){
            JOptionPane.showMessageDialog(null,"Account number cannot contains any letters,characters, and Special Characters..","Invalid",JOptionPane.ERROR_MESSAGE);
        } else if(MatchWhiteSpace.find()){
            JOptionPane.showMessageDialog(null,"Account Number and Name cannot accept white space..","Invalid",JOptionPane.ERROR_MESSAGE);
        }
        else {
            boolean isFound = false;
            try{
            int AccountNumber = Integer.parseInt(getAccNumber);
            if(AccountNumber <= 0){
                JOptionPane.showMessageDialog(null,"Account number cannot be less than or Equal to Zero.","Invalid.",JOptionPane.ERROR_MESSAGE);
            } else if(AccountNumber >= 100000000){
                JOptionPane.showMessageDialog(null,"Account number cannot exceed 9 Digits.","Invalid.",JOptionPane.ERROR_MESSAGE);
            } else {
                isFound = true;
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Invalid!.","Invalid.",JOptionPane.ERROR_MESSAGE);
           }
         
          if(isFound){
        setVisible(false);
        
        MenuBank mb = new MenuBank(MainFrame.this);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                mb.setVisible(true);
            }
        });
          }
      }

    }//GEN-LAST:event_TO_PROCEEDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public javax.swing.JTextField getUserName() {
        return UserName;
    }

    public javax.swing.JTextField getACCOUNT_NO() {
        return ACCOUNT_NO;
    }

    public javax.swing.JButton getBTN_EXIT() {
        return BTN_EXIT;
    }

    public javax.swing.JButton getTO_PROCEED() {
        return TO_PROCEED;
    }

    public javax.swing.JLabel getBankLabel() {
        return BankLabel;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ACCOUNT_NO;
    private javax.swing.JButton BTN_EXIT;
    private javax.swing.JLabel BankLabel;
    private javax.swing.JLabel LB_ACCNO;
    private javax.swing.JLabel LB_NAME;
    private javax.swing.JButton TO_PROCEED;
    private javax.swing.JTextField UserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
