/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import javax.swing.*;
import java.util.Random;
/**
 *
 * @author James
 */
public class MenuBank extends javax.swing.JFrame {
    private MainFrame mf;
    
    public MainFrame newFrame;
    
    public StringBuilder SavingsAccount = new StringBuilder();
    public StringBuilder HeaderContent = new StringBuilder();
    public StringBuilder LoaningAccount = new StringBuilder();
    
//    public static JLabel NameGet2;
//    public static JLabel AccGet2;
    
    
/**
     * Creates new form MenuBank
     */
    double addMoney;
    double Money;
    
    
        // This make the User Input in MainFrame visible..
        public MenuBank(MainFrame mainFrame) {
        initComponents();
        this.mf = mainFrame;
        Random rand = new Random();
        
        NameGet.setText("| "+ mf.getUserName().getText());
        getACCNO.setText("| "+mf.getACCOUNT_NO().getText());
        
        setTitle("Menu Banking");
        int SerialNumber = rand.nextInt(1000000);
        String getSerialNumber = Integer.toString(SerialNumber);
        

        HeaderContent.append("------------------------------------------------------------------------------------------------");
        HeaderContent.append("\n");
        HeaderContent.append("\t          Grand Summit Bank System");
        HeaderContent.append("\n");
        HeaderContent.append("\t          Serial Number: " + getSerialNumber);
        HeaderContent.append("\n");
        HeaderContent.append("\n-------------------------------------------------------------------------------------------------\n");
        HeaderContent.append("\t          Name: " + NameGet.getText());
        HeaderContent.append("\n");
        HeaderContent.append("\t          Account Number: " + getACCNO.getText());
        HeaderContent.append("\n");
        HeaderContent.append("\n");
        HeaderContent.append("\n");
        HeaderContent.append("\n");
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        NavTop = new javax.swing.JPanel();
        NameUser = new javax.swing.JLabel();
        AccountNoUser = new javax.swing.JLabel();
        NameGet = new javax.swing.JLabel();
        getACCNO = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Withdraw = new javax.swing.JButton();
        Deposit = new javax.swing.JButton();
        Savings = new javax.swing.JButton();
        BankHist = new javax.swing.JButton();
        BTN_PAYLOAN = new javax.swing.JButton();
        Buy_Game = new javax.swing.JButton();
        Submit_btn = new javax.swing.JButton();
        BankName = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to Menu");

        jButton5.setText("jButton5");

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NavTop.setBackground(new java.awt.Color(204, 204, 204));

        NameUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NameUser.setText("Name:");

        AccountNoUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccountNoUser.setText("Account Number:");

        NameGet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        getACCNO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout NavTopLayout = new javax.swing.GroupLayout(NavTop);
        NavTop.setLayout(NavTopLayout);
        NavTopLayout.setHorizontalGroup(
            NavTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavTopLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(NavTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AccountNoUser)
                    .addComponent(NameUser))
                .addGap(18, 18, 18)
                .addGroup(NavTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameGet, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getACCNO, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144))
        );
        NavTopLayout.setVerticalGroup(
            NavTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameGet, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NavTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getACCNO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountNoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Withdraw.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Withdraw.setText("WITHDRAWAL");
        Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawActionPerformed(evt);
            }
        });

        Deposit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Deposit.setText("DEPOSIT");
        Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositActionPerformed(evt);
            }
        });

        Savings.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Savings.setText("SAVINGS");
        Savings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingsActionPerformed(evt);
            }
        });

        BankHist.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BankHist.setText("BANK HISTORY");
        BankHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankHistActionPerformed(evt);
            }
        });

        BTN_PAYLOAN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BTN_PAYLOAN.setText("EXIT");
        BTN_PAYLOAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PAYLOANActionPerformed(evt);
            }
        });

        Buy_Game.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Buy_Game.setText("LOANING");
        Buy_Game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buy_GameActionPerformed(evt);
            }
        });

        Submit_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Submit_btn.setText("SUBMIT");
        Submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BTN_PAYLOAN, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buy_Game, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Savings, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BankHist, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(Submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Savings, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankHist, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_PAYLOAN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buy_Game, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(Submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        BankName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BankName.setText("Grand Summit Bank System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NavTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BankName)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NavTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BankName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositActionPerformed
      try {
        String inputMoney = JOptionPane.showInputDialog(null,"Please Enter an Amount: ","Depositing Money",JOptionPane.PLAIN_MESSAGE);
        if(inputMoney.isEmpty()){
            JOptionPane.showMessageDialog(null,"What?????","Error",JOptionPane.ERROR_MESSAGE);
        }
      Money = Double.parseDouble(inputMoney);
      
      
      
      if(Money < 0){
          JOptionPane.showMessageDialog(null, "Money Cannot be negative!","Invalid",JOptionPane.ERROR_MESSAGE);
      } else {
      addMoney += Money;
      
      SavingsAccount.append("\t          You Deposited: " + String.format("%.2f", Money) + "$");
      SavingsAccount.append("\n");
      }
      } catch(NumberFormatException e){
          JOptionPane.showMessageDialog(null, "Invalid Inputation!","Invalid",JOptionPane.ERROR_MESSAGE);
      } 
     
    }//GEN-LAST:event_DepositActionPerformed

    private void BTN_PAYLOANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PAYLOANActionPerformed
        dispose();
    }//GEN-LAST:event_BTN_PAYLOANActionPerformed

    private void Buy_GameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buy_GameActionPerformed
       dispose();
       LoanBank lb = new LoanBank(this);
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                lb.setVisible(true);
            }
        });
       
    }//GEN-LAST:event_Buy_GameActionPerformed

    public JLabel getNameGet(){
        return NameGet;
    }
    
    public JLabel showACCNO(){
        return getACCNO;
    }
    private void Submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_btnActionPerformed
        
    }//GEN-LAST:event_Submit_btnActionPerformed

    private void WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawActionPerformed
        try {
            String toWithdraw = JOptionPane.showInputDialog(null,"Please Enter an amount to Withdraw: ","Withdrawal",JOptionPane.PLAIN_MESSAGE);
            if(toWithdraw.isEmpty()){
                JOptionPane.showMessageDialog(null,"What?????","Error",JOptionPane.ERROR_MESSAGE);
            }
            double WithdrawedMoney = Double.parseDouble(toWithdraw);
            if(WithdrawedMoney > addMoney){
               JOptionPane.showMessageDialog(null,"Invalid Withdrawal!!","Invalid",JOptionPane.ERROR_MESSAGE);

            } else if(WithdrawedMoney < 0){
                JOptionPane.showMessageDialog(null,"Withdrawal money cannot be negative!!","Invalid",JOptionPane.ERROR_MESSAGE);
            } else {
                addMoney = addMoney - WithdrawedMoney;
                SavingsAccount.append("\t          You Withdrawed: " + String.format("%.2f", WithdrawedMoney) + "$");
                SavingsAccount.append("\n");
                
            }
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Invalid Inputation!","Invalid",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_WithdrawActionPerformed

    private void BankHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankHistActionPerformed
        dispose();
        SavingSA SSA = new SavingSA(MenuBank.this);
        java.awt.EventQueue.invokeLater(() -> {
            SSA.setVisible(true);
        });
        
    }//GEN-LAST:event_BankHistActionPerformed

    private void SavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingsActionPerformed
        
        JOptionPane.showMessageDialog(null,"Total Balance: "+String.format("%.2f", addMoney)+"$","Savings Account",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_SavingsActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
   public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(MenuBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(MenuBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(MenuBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(MenuBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNoUser;
    private javax.swing.JButton BTN_PAYLOAN;
    private javax.swing.JButton BankHist;
    private javax.swing.JLabel BankName;
    private javax.swing.JButton Buy_Game;
    private javax.swing.JButton Deposit;
    private javax.swing.JLabel NameGet;
    private javax.swing.JLabel NameUser;
    private javax.swing.JPanel NavTop;
    private javax.swing.JButton Savings;
    private javax.swing.JButton Submit_btn;
    private javax.swing.JButton Withdraw;
    private javax.swing.JLabel getACCNO;
    private javax.swing.JButton jButton5;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
